# Generated by Django 5.1.6 on 2025-04-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=5, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='signinrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='signinrecord',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signinrecord',
            name='student_id',
        ),
        migrations.AddField(
            model_name='signinrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sign_in.studentreference'),
        ),
    ]
