# Generated by Django 5.1.6 on 2025-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0003_studentreference_remove_signinrecord_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreference',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
