# Generated by Django 5.1.6 on 2025-04-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentReference',
        ),
    ]
